#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "bfc5fdd338f340898608a66d1dac0cae" }
]

[assets]
directory = "./public"
